//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vmPing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vmPing.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string Button_Ping {
            get {
                return ResourceManager.GetString("Button_Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DialogButton_Cancel {
            get {
                return ResourceManager.GetString("DialogButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DialogButton_Edit {
            get {
                return ResourceManager.GetString("DialogButton_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string DialogButton_New {
            get {
                return ResourceManager.GetString("DialogButton_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DialogButton_OK {
            get {
                return ResourceManager.GetString("DialogButton_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string DialogButton_Overwrite {
            get {
                return ResourceManager.GetString("DialogButton_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string DialogButton_Remove {
            get {
                return ResourceManager.GetString("DialogButton_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DialogButton_Save {
            get {
                return ResourceManager.GetString("DialogButton_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string DialogTitle_ConfirmDelete {
            get {
                return ResourceManager.GetString("DialogTitle_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogTitle_Error {
            get {
                return ResourceManager.GetString("DialogTitle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DialogTitle_Warning {
            get {
                return ResourceManager.GetString("DialogTitle_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to down.
        /// </summary>
        public static string Email_Down {
            get {
                return ResourceManager.GetString("Email_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string Email_Error {
            get {
                return ResourceManager.GetString("Email_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Email_Host {
            get {
                return ResourceManager.GetString("Email_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up.
        /// </summary>
        public static string Email_Up {
            get {
                return ResourceManager.GetString("Email_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string Email_Verb {
            get {
                return ResourceManager.GetString("Email_Verb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add alias..
        /// </summary>
        public static string Error_AddAlias {
            get {
                return ResourceManager.GetString("Error_AddAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create vmPing configuration file..
        /// </summary>
        public static string Error_CreateConfig {
            get {
                return ResourceManager.GetString("Error_CreateConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create directory for vmPing configuration file..
        /// </summary>
        public static string Error_CreateDirectory {
            get {
                return ResourceManager.GetString("Error_CreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete alias..
        /// </summary>
        public static string Error_DeleteAlias {
            get {
                return ResourceManager.GetString("Error_DeleteAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch a new instance of vmPing..
        /// </summary>
        public static string Error_FailedToLaunch {
            get {
                return ResourceManager.GetString("Error_FailedToLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load aliases..
        /// </summary>
        public static string Error_LoadAlias {
            get {
                return ResourceManager.GetString("Error_LoadAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load configuration file..
        /// </summary>
        public static string Error_LoadConfig {
            get {
                return ResourceManager.GetString("Error_LoadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read configuration file..
        /// </summary>
        public static string Error_ReadConfig {
            get {
                return ResourceManager.GetString("Error_ReadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upgrade configuration file..
        /// </summary>
        public static string Error_UpgradeConfig {
            get {
                return ResourceManager.GetString("Error_UpgradeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vmPing - Error.
        /// </summary>
        public static string Error_WindowTitle {
            get {
                return ResourceManager.GetString("Error_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write to configuration file..
        /// </summary>
        public static string Error_WriteConfig {
            get {
                return ResourceManager.GetString("Error_WriteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string ManageAliases_Alias {
            get {
                return ResourceManager.GetString("ManageAliases_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your aliases.
        /// </summary>
        public static string ManageAliases_Header {
            get {
                return ResourceManager.GetString("ManageAliases_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string ManageAliases_Host {
            get {
                return ResourceManager.GetString("ManageAliases_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove.
        /// </summary>
        public static string ManageAliases_Warn_DeleteA {
            get {
                return ResourceManager.GetString("ManageAliases_Warn_DeleteA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from your aliases?.
        /// </summary>
        public static string ManageAliases_Warn_DeleteB {
            get {
                return ResourceManager.GetString("ManageAliases_Warn_DeleteB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        public static string ManageAliases_WindowTitle {
            get {
                return ResourceManager.GetString("ManageAliases_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your favorites.
        /// </summary>
        public static string ManageFavorites_Header {
            get {
                return ResourceManager.GetString("ManageFavorites_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove.
        /// </summary>
        public static string ManageFavorites_Warn_DeleteA {
            get {
                return ResourceManager.GetString("ManageFavorites_Warn_DeleteA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from your favorites?.
        /// </summary>
        public static string ManageFavorites_Warn_DeleteB {
            get {
                return ResourceManager.GetString("ManageFavorites_Warn_DeleteB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string ManageFavorites_WindowTitle {
            get {
                return ResourceManager.GetString("ManageFavorites_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        public static string Menu_Aliases {
            get {
                return ResourceManager.GetString("Menu_Aliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Sets.
        /// </summary>
        public static string Menu_FavoriteSets {
            get {
                return ResourceManager.GetString("Menu_FavoriteSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Host.
        /// </summary>
        public static string Menu_FloodHost {
            get {
                return ResourceManager.GetString("Menu_FloodHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Aliases.
        /// </summary>
        public static string Menu_ManageAliases {
            get {
                return ResourceManager.GetString("Menu_ManageAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Favorites.
        /// </summary>
        public static string Menu_ManageFavorites {
            get {
                return ResourceManager.GetString("Menu_ManageFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Menu_Options {
            get {
                return ResourceManager.GetString("Menu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Alerts.
        /// </summary>
        public static string Menu_PopupAlerts {
            get {
                return ResourceManager.GetString("Menu_PopupAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Favorite Set.
        /// </summary>
        public static string Menu_SaveToFavorites {
            get {
                return ResourceManager.GetString("Menu_SaveToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status History.
        /// </summary>
        public static string Menu_StatusHistory {
            get {
                return ResourceManager.GetString("Menu_StatusHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traceroute.
        /// </summary>
        public static string Menu_Traceroute {
            get {
                return ResourceManager.GetString("Menu_Traceroute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string Milliseconds_Symbol {
            get {
                return ResourceManager.GetString("Milliseconds_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string NewAlias_Alias {
            get {
                return ResourceManager.GetString("NewAlias_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid alias..
        /// </summary>
        public static string NewAlias_Error_InvalidAlias {
            get {
                return ResourceManager.GetString("NewAlias_Error_InvalidAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid host name..
        /// </summary>
        public static string NewAlias_Error_InvalidHost {
            get {
                return ResourceManager.GetString("NewAlias_Error_InvalidHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new alias.
        /// </summary>
        public static string NewAlias_Header {
            get {
                return ResourceManager.GetString("NewAlias_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string NewAlias_Host {
            get {
                return ResourceManager.GetString("NewAlias_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid name for this favorite set..
        /// </summary>
        public static string NewFavorite_Error_InvalidName {
            get {
                return ResourceManager.GetString("NewFavorite_Error_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new favorite set.
        /// </summary>
        public static string NewFavorite_Header {
            get {
                return ResourceManager.GetString("NewFavorite_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Hosts.
        /// </summary>
        public static string NewFavorite_SelectedHostsHeader {
            get {
                return ResourceManager.GetString("NewFavorite_SelectedHostsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a title.
        /// </summary>
        public static string NewFavorite_Title {
            get {
                return ResourceManager.GetString("NewFavorite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists.  Would you like to overwrite?.
        /// </summary>
        public static string NewFavorite_Warn_AlreadyExists {
            get {
                return ResourceManager.GetString("NewFavorite_Warn_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string Notification_Always {
            get {
                return ResourceManager.GetString("Notification_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Notification_Never {
            get {
                return ResourceManager.GetString("Notification_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Minimized.
        /// </summary>
        public static string Notification_WhenMinimized {
            get {
                return ResourceManager.GetString("Notification_WhenMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string Probe_Error {
            get {
                return ResourceManager.GetString("Probe_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply  [Host unreachable].
        /// </summary>
        public static string Probe_HostUnreachable {
            get {
                return ResourceManager.GetString("Probe_HostUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port number..
        /// </summary>
        public static string Probe_InvalidPort {
            get {
                return ResourceManager.GetString("Probe_InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply  [Network unreachable].
        /// </summary>
        public static string Probe_NetUnreachable {
            get {
                return ResourceManager.GetString("Probe_NetUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Probe_Port {
            get {
                return ResourceManager.GetString("Probe_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSED.
        /// </summary>
        public static string Probe_PortClosed {
            get {
                return ResourceManager.GetString("Probe_PortClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN.
        /// </summary>
        public static string Probe_PortOpen {
            get {
                return ResourceManager.GetString("Probe_PortOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply from.
        /// </summary>
        public static string Probe_Reply {
            get {
                return ResourceManager.GetString("Probe_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinging.
        /// </summary>
        public static string Probe_StartPing {
            get {
                return ResourceManager.GetString("Probe_StartPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost:.
        /// </summary>
        public static string Probe_Stat_Lost {
            get {
                return ResourceManager.GetString("Probe_Stat_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received:.
        /// </summary>
        public static string Probe_Stat_Received {
            get {
                return ResourceManager.GetString("Probe_Stat_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent:.
        /// </summary>
        public static string Probe_Stat_Sent {
            get {
                return ResourceManager.GetString("Probe_Stat_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timed out..
        /// </summary>
        public static string Probe_Timeout {
            get {
                return ResourceManager.GetString("Probe_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve hostname..
        /// </summary>
        public static string Probe_UnableToResolve {
            get {
                return ResourceManager.GetString("Probe_UnableToResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply  [Unreachable].
        /// </summary>
        public static string Probe_Unreachable {
            get {
                return ResourceManager.GetString("Probe_Unreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to down.
        /// </summary>
        public static string StatusChange_Down {
            get {
                return ResourceManager.GetString("StatusChange_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [error].
        /// </summary>
        public static string StatusChange_Error {
            get {
                return ResourceManager.GetString("StatusChange_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high latency.
        /// </summary>
        public static string StatusChange_LatencyHigh {
            get {
                return ResourceManager.GetString("StatusChange_LatencyHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal latency.
        /// </summary>
        public static string StatusChange_LatencyNormal {
            get {
                return ResourceManager.GetString("StatusChange_LatencyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started.
        /// </summary>
        public static string StatusChange_Start {
            get {
                return ResourceManager.GetString("StatusChange_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stopped.
        /// </summary>
        public static string StatusChange_Stop {
            get {
                return ResourceManager.GetString("StatusChange_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up.
        /// </summary>
        public static string StatusChange_Up {
            get {
                return ResourceManager.GetString("StatusChange_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No status history.
        /// </summary>
        public static string StatusHistory_NoChanges {
            get {
                return ResourceManager.GetString("StatusHistory_NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a host changes between down or up, it&apos;ll show up here.
        /// </summary>
        public static string StatusHistory_NoChangesDescription {
            get {
                return ResourceManager.GetString("StatusHistory_NoChangesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status History.
        /// </summary>
        public static string StatusHistory_WindowTitle {
            get {
                return ResourceManager.GetString("StatusHistory_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add Host.
        /// </summary>
        public static string Toolbar_Add {
            get {
                return ResourceManager.GetString("Toolbar_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Columns.
        /// </summary>
        public static string Toolbar_Columns {
            get {
                return ResourceManager.GetString("Toolbar_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start All (F5).
        /// </summary>
        public static string Toolbar_StartAll {
            get {
                return ResourceManager.GetString("Toolbar_StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stop All (F5).
        /// </summary>
        public static string Toolbar_StopAll {
            get {
                return ResourceManager.GetString("Toolbar_StopAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Tooltip_Close {
            get {
                return ResourceManager.GetString("Tooltip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit alias.
        /// </summary>
        public static string Tooltip_EditAlias {
            get {
                return ResourceManager.GetString("Tooltip_EditAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open isolated view.
        /// </summary>
        public static string Tooltip_IsolatedView {
            get {
                return ResourceManager.GetString("Tooltip_IsolatedView", resourceCulture);
            }
        }

        // [Certo] FASE 5/i18n — propriedades adicionadas à mão (sem ResGen/VS
        // neste ambiente), seguindo exatamente o padrão gerado acima. Se o
        // arquivo for regenerado por ferramenta um dia, elas voltam sozinhas
        // a partir do .resx.

        /// <summary>
        ///   Looks up a localized string similar to Enter a hostname.
        /// </summary>
        public static string MainWindow_Watermark {
            get {
                return ResourceManager.GetString("MainWindow_Watermark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input Addresses.
        /// </summary>
        public static string Menu_InputAddresses {
            get {
                return ResourceManager.GetString("Menu_InputAddresses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New vmPing Instance.
        /// </summary>
        public static string Menu_NewInstance {
            get {
                return ResourceManager.GetString("Menu_NewInstance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit vmPing.
        /// </summary>
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Options_Language {
            get {
                return ResourceManager.GetString("Options_Language", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto (system language).
        /// </summary>
        public static string Options_LanguageAuto {
            get {
                return ResourceManager.GetString("Options_LanguageAuto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language changes take effect after restarting vmPing.
        /// </summary>
        public static string Options_LanguageRestart {
            get {
                return ResourceManager.GetString("Options_LanguageRestart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_WindowTitle {
            get {
                return ResourceManager.GetString("Help_WindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_Intro {
            get {
                return ResourceManager.GetString("Help_Intro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_BasicUsage {
            get {
                return ResourceManager.GetString("Help_BasicUsage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_MonitorHost_Title {
            get {
                return ResourceManager.GetString("Help_MonitorHost_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_MonitorHost_Body {
            get {
                return ResourceManager.GetString("Help_MonitorHost_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_AddMonitor_Title {
            get {
                return ResourceManager.GetString("Help_AddMonitor_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_AddMonitor_Body {
            get {
                return ResourceManager.GetString("Help_AddMonitor_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_RemoveMonitor_Title {
            get {
                return ResourceManager.GetString("Help_RemoveMonitor_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_RemoveMonitor_Body {
            get {
                return ResourceManager.GetString("Help_RemoveMonitor_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_Columns_Title {
            get {
                return ResourceManager.GetString("Help_Columns_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_Columns_Body {
            get {
                return ResourceManager.GetString("Help_Columns_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_ExtraFeatures {
            get {
                return ResourceManager.GetString("Help_ExtraFeatures", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_PortMonitor_Title {
            get {
                return ResourceManager.GetString("Help_PortMonitor_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_PortMonitor_Body {
            get {
                return ResourceManager.GetString("Help_PortMonitor_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_TraceRoute_Title {
            get {
                return ResourceManager.GetString("Help_TraceRoute_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_TraceRoute_Body {
            get {
                return ResourceManager.GetString("Help_TraceRoute_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_FloodHost_Title {
            get {
                return ResourceManager.GetString("Help_FloodHost_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_FloodHost_Body {
            get {
                return ResourceManager.GetString("Help_FloodHost_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_OptionsSection {
            get {
                return ResourceManager.GetString("Help_OptionsSection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_PingInterval_Title {
            get {
                return ResourceManager.GetString("Help_PingInterval_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_PingInterval_Body {
            get {
                return ResourceManager.GetString("Help_PingInterval_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_PingTimeout_Title {
            get {
                return ResourceManager.GetString("Help_PingTimeout_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_PingTimeout_Body {
            get {
                return ResourceManager.GetString("Help_PingTimeout_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_Email_Title {
            get {
                return ResourceManager.GetString("Help_Email_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_Email_Body {
            get {
                return ResourceManager.GetString("Help_Email_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_AlwaysOnTop_Title {
            get {
                return ResourceManager.GetString("Help_AlwaysOnTop_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_AlwaysOnTop_Body {
            get {
                return ResourceManager.GetString("Help_AlwaysOnTop_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_LogOutput_Title {
            get {
                return ResourceManager.GetString("Help_LogOutput_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_LogOutput_Body {
            get {
                return ResourceManager.GetString("Help_LogOutput_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_CommandLine {
            get {
                return ResourceManager.GetString("Help_CommandLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_CmdSyntax {
            get {
                return ResourceManager.GetString("Help_CmdSyntax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_CmdInterval {
            get {
                return ResourceManager.GetString("Help_CmdInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_CmdTimeout {
            get {
                return ResourceManager.GetString("Help_CmdTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help content).
        /// </summary>
        public static string Help_CmdTarget {
            get {
                return ResourceManager.GetString("Help_CmdTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Menu_Nslookup).
        /// </summary>
        public static string Menu_Nslookup {
            get {
                return ResourceManager.GetString("Menu_Nslookup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Menu_Dig).
        /// </summary>
        public static string Menu_Dig {
            get {
                return ResourceManager.GetString("Menu_Dig", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (DnsLookup_Watermark).
        /// </summary>
        public static string DnsLookup_Watermark {
            get {
                return ResourceManager.GetString("DnsLookup_Watermark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (DnsLookup_Run).
        /// </summary>
        public static string DnsLookup_Run {
            get {
                return ResourceManager.GetString("DnsLookup_Run", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (DnsLookup_Type).
        /// </summary>
        public static string DnsLookup_Type {
            get {
                return ResourceManager.GetString("DnsLookup_Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (DnsLookup_Server).
        /// </summary>
        public static string DnsLookup_Server {
            get {
                return ResourceManager.GetString("DnsLookup_Server", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (DnsLookup_TypeDefault).
        /// </summary>
        public static string DnsLookup_TypeDefault {
            get {
                return ResourceManager.GetString("DnsLookup_TypeDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (DnsLookup_WindowTitle).
        /// </summary>
        public static string DnsLookup_WindowTitle {
            get {
                return ResourceManager.GetString("DnsLookup_WindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (EditAlias_WindowTitle).
        /// </summary>
        public static string EditAlias_WindowTitle {
            get {
                return ResourceManager.GetString("EditAlias_WindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (EditAlias_Prompt).
        /// </summary>
        public static string EditAlias_Prompt {
            get {
                return ResourceManager.GetString("EditAlias_Prompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (EditAlias_Watermark).
        /// </summary>
        public static string EditAlias_Watermark {
            get {
                return ResourceManager.GetString("EditAlias_Watermark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (FloodHost_WindowTitle).
        /// </summary>
        public static string FloodHost_WindowTitle {
            get {
                return ResourceManager.GetString("FloodHost_WindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (FloodHost_Sent).
        /// </summary>
        public static string FloodHost_Sent {
            get {
                return ResourceManager.GetString("FloodHost_Sent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (FloodHost_Received).
        /// </summary>
        public static string FloodHost_Received {
            get {
                return ResourceManager.GetString("FloodHost_Received", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (FloodHost_Lost).
        /// </summary>
        public static string FloodHost_Lost {
            get {
                return ResourceManager.GetString("FloodHost_Lost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (FloodHost_Info).
        /// </summary>
        public static string FloodHost_Info {
            get {
                return ResourceManager.GetString("FloodHost_Info", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (FloodHost_InProgress).
        /// </summary>
        public static string FloodHost_InProgress {
            get {
                return ResourceManager.GetString("FloodHost_InProgress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (MultiInput_Prompt).
        /// </summary>
        public static string MultiInput_Prompt {
            get {
                return ResourceManager.GetString("MultiInput_Prompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (NewAlias_WindowTitle).
        /// </summary>
        public static string NewAlias_WindowTitle {
            get {
                return ResourceManager.GetString("NewAlias_WindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (NewAlias_Header2).
        /// </summary>
        public static string NewAlias_Header2 {
            get {
                return ResourceManager.GetString("NewAlias_Header2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (NewConfig_WindowTitle).
        /// </summary>
        public static string NewConfig_WindowTitle {
            get {
                return ResourceManager.GetString("NewConfig_WindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (NewConfig_Line1).
        /// </summary>
        public static string NewConfig_Line1 {
            get {
                return ResourceManager.GetString("NewConfig_Line1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (NewConfig_Line2).
        /// </summary>
        public static string NewConfig_Line2 {
            get {
                return ResourceManager.GetString("NewConfig_Line2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (NewConfig_Line3).
        /// </summary>
        public static string NewConfig_Line3 {
            get {
                return ResourceManager.GetString("NewConfig_Line3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (NewConfig_Portable).
        /// </summary>
        public static string NewConfig_Portable {
            get {
                return ResourceManager.GetString("NewConfig_Portable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (NewFavorite_WindowTitle).
        /// </summary>
        public static string NewFavorite_WindowTitle {
            get {
                return ResourceManager.GetString("NewFavorite_WindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (NewFavorite_Header2).
        /// </summary>
        public static string NewFavorite_Header2 {
            get {
                return ResourceManager.GetString("NewFavorite_Header2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (NewFavorite_TitleLabel).
        /// </summary>
        public static string NewFavorite_TitleLabel {
            get {
                return ResourceManager.GetString("NewFavorite_TitleLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (NewFavorite_HostsLabel).
        /// </summary>
        public static string NewFavorite_HostsLabel {
            get {
                return ResourceManager.GetString("NewFavorite_HostsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_TabGeneral).
        /// </summary>
        public static string Options_TabGeneral {
            get {
                return ResourceManager.GetString("Options_TabGeneral", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_ProbeOptions).
        /// </summary>
        public static string Options_ProbeOptions {
            get {
                return ResourceManager.GetString("Options_ProbeOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_PingInterval).
        /// </summary>
        public static string Options_PingInterval {
            get {
                return ResourceManager.GetString("Options_PingInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_Seconds).
        /// </summary>
        public static string Options_Seconds {
            get {
                return ResourceManager.GetString("Options_Seconds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_Minutes).
        /// </summary>
        public static string Options_Minutes {
            get {
                return ResourceManager.GetString("Options_Minutes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_Hours).
        /// </summary>
        public static string Options_Hours {
            get {
                return ResourceManager.GetString("Options_Hours", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_PingTimeout).
        /// </summary>
        public static string Options_PingTimeout {
            get {
                return ResourceManager.GetString("Options_PingTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_AlertThreshold).
        /// </summary>
        public static string Options_AlertThreshold {
            get {
                return ResourceManager.GetString("Options_AlertThreshold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_DroppedPings).
        /// </summary>
        public static string Options_DroppedPings {
            get {
                return ResourceManager.GetString("Options_DroppedPings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_Startup).
        /// </summary>
        public static string Options_Startup {
            get {
                return ResourceManager.GetString("Options_Startup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_StartupPrompt).
        /// </summary>
        public static string Options_StartupPrompt {
            get {
                return ResourceManager.GetString("Options_StartupPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_StartBlank).
        /// </summary>
        public static string Options_StartBlank {
            get {
                return ResourceManager.GetString("Options_StartBlank", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_StartList).
        /// </summary>
        public static string Options_StartList {
            get {
                return ResourceManager.GetString("Options_StartList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_StartFavorite).
        /// </summary>
        public static string Options_StartFavorite {
            get {
                return ResourceManager.GetString("Options_StartFavorite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_ProbeCount).
        /// </summary>
        public static string Options_ProbeCount {
            get {
                return ResourceManager.GetString("Options_ProbeCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_ColumnCount).
        /// </summary>
        public static string Options_ColumnCount {
            get {
                return ResourceManager.GetString("Options_ColumnCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_SelectFavorite).
        /// </summary>
        public static string Options_SelectFavorite {
            get {
                return ResourceManager.GetString("Options_SelectFavorite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_TabAdvanced).
        /// </summary>
        public static string Options_TabAdvanced {
            get {
                return ResourceManager.GetString("Options_TabAdvanced", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_AdvancedIcmp).
        /// </summary>
        public static string Options_AdvancedIcmp {
            get {
                return ResourceManager.GetString("Options_AdvancedIcmp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_Ttl).
        /// </summary>
        public static string Options_Ttl {
            get {
                return ResourceManager.GetString("Options_Ttl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_Hops).
        /// </summary>
        public static string Options_Hops {
            get {
                return ResourceManager.GetString("Options_Hops", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_PacketSize).
        /// </summary>
        public static string Options_PacketSize {
            get {
                return ResourceManager.GetString("Options_PacketSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_Bytes).
        /// </summary>
        public static string Options_Bytes {
            get {
                return ResourceManager.GetString("Options_Bytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_CustomPacket).
        /// </summary>
        public static string Options_CustomPacket {
            get {
                return ResourceManager.GetString("Options_CustomPacket", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_TotalPacketSize).
        /// </summary>
        public static string Options_TotalPacketSize {
            get {
                return ResourceManager.GetString("Options_TotalPacketSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_DontFragment).
        /// </summary>
        public static string Options_DontFragment {
            get {
                return ResourceManager.GetString("Options_DontFragment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_DontFragmentTip).
        /// </summary>
        public static string Options_DontFragmentTip {
            get {
                return ResourceManager.GetString("Options_DontFragmentTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_TabNotifications).
        /// </summary>
        public static string Options_TabNotifications {
            get {
                return ResourceManager.GetString("Options_TabNotifications", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_PopupInfo).
        /// </summary>
        public static string Options_PopupInfo {
            get {
                return ResourceManager.GetString("Options_PopupInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_PopupDisabled).
        /// </summary>
        public static string Options_PopupDisabled {
            get {
                return ResourceManager.GetString("Options_PopupDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_PopupWhenMinimized).
        /// </summary>
        public static string Options_PopupWhenMinimized {
            get {
                return ResourceManager.GetString("Options_PopupWhenMinimized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_PopupAlways).
        /// </summary>
        public static string Options_PopupAlways {
            get {
                return ResourceManager.GetString("Options_PopupAlways", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_AutoDismiss).
        /// </summary>
        public static string Options_AutoDismiss {
            get {
                return ResourceManager.GetString("Options_AutoDismiss", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_AutoDismissTip).
        /// </summary>
        public static string Options_AutoDismissTip {
            get {
                return ResourceManager.GetString("Options_AutoDismissTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_TabEmail).
        /// </summary>
        public static string Options_TabEmail {
            get {
                return ResourceManager.GetString("Options_TabEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_EmailAlerts).
        /// </summary>
        public static string Options_EmailAlerts {
            get {
                return ResourceManager.GetString("Options_EmailAlerts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_EnableEmail).
        /// </summary>
        public static string Options_EnableEmail {
            get {
                return ResourceManager.GetString("Options_EnableEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_EnableEmailTip).
        /// </summary>
        public static string Options_EnableEmailTip {
            get {
                return ResourceManager.GetString("Options_EnableEmailTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_ServerInfo).
        /// </summary>
        public static string Options_ServerInfo {
            get {
                return ResourceManager.GetString("Options_ServerInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_SmtpServer).
        /// </summary>
        public static string Options_SmtpServer {
            get {
                return ResourceManager.GetString("Options_SmtpServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_Port).
        /// </summary>
        public static string Options_Port {
            get {
                return ResourceManager.GetString("Options_Port", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_EnableSsl).
        /// </summary>
        public static string Options_EnableSsl {
            get {
                return ResourceManager.GetString("Options_EnableSsl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_RequiresAuth).
        /// </summary>
        public static string Options_RequiresAuth {
            get {
                return ResourceManager.GetString("Options_RequiresAuth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_Username).
        /// </summary>
        public static string Options_Username {
            get {
                return ResourceManager.GetString("Options_Username", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_Password).
        /// </summary>
        public static string Options_Password {
            get {
                return ResourceManager.GetString("Options_Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_EmailAddresses).
        /// </summary>
        public static string Options_EmailAddresses {
            get {
                return ResourceManager.GetString("Options_EmailAddresses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_Recipient).
        /// </summary>
        public static string Options_Recipient {
            get {
                return ResourceManager.GetString("Options_Recipient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_FromAddress).
        /// </summary>
        public static string Options_FromAddress {
            get {
                return ResourceManager.GetString("Options_FromAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_Test).
        /// </summary>
        public static string Options_Test {
            get {
                return ResourceManager.GetString("Options_Test", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_TabSounds).
        /// </summary>
        public static string Options_TabSounds {
            get {
                return ResourceManager.GetString("Options_TabSounds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_AudioAlerts).
        /// </summary>
        public static string Options_AudioAlerts {
            get {
                return ResourceManager.GetString("Options_AudioAlerts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_AudioDown).
        /// </summary>
        public static string Options_AudioDown {
            get {
                return ResourceManager.GetString("Options_AudioDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_AudioDownTip).
        /// </summary>
        public static string Options_AudioDownTip {
            get {
                return ResourceManager.GetString("Options_AudioDownTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_AudioPath).
        /// </summary>
        public static string Options_AudioPath {
            get {
                return ResourceManager.GetString("Options_AudioPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_Browse).
        /// </summary>
        public static string Options_Browse {
            get {
                return ResourceManager.GetString("Options_Browse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_AudioUp).
        /// </summary>
        public static string Options_AudioUp {
            get {
                return ResourceManager.GetString("Options_AudioUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_AudioUpTip).
        /// </summary>
        public static string Options_AudioUpTip {
            get {
                return ResourceManager.GetString("Options_AudioUpTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_TabLogging).
        /// </summary>
        public static string Options_TabLogging {
            get {
                return ResourceManager.GetString("Options_TabLogging", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_LogOutput).
        /// </summary>
        public static string Options_LogOutput {
            get {
                return ResourceManager.GetString("Options_LogOutput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_WriteLog).
        /// </summary>
        public static string Options_WriteLog {
            get {
                return ResourceManager.GetString("Options_WriteLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_WriteLogTip).
        /// </summary>
        public static string Options_WriteLogTip {
            get {
                return ResourceManager.GetString("Options_WriteLogTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_LogPath).
        /// </summary>
        public static string Options_LogPath {
            get {
                return ResourceManager.GetString("Options_LogPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_LogStatus).
        /// </summary>
        public static string Options_LogStatus {
            get {
                return ResourceManager.GetString("Options_LogStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_LogStatusTip).
        /// </summary>
        public static string Options_LogStatusTip {
            get {
                return ResourceManager.GetString("Options_LogStatusTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_LogStatusPath).
        /// </summary>
        public static string Options_LogStatusPath {
            get {
                return ResourceManager.GetString("Options_LogStatusPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_TabDisplay).
        /// </summary>
        public static string Options_TabDisplay {
            get {
                return ResourceManager.GetString("Options_TabDisplay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_DisplayOptions).
        /// </summary>
        public static string Options_DisplayOptions {
            get {
                return ResourceManager.GetString("Options_DisplayOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_AlwaysOnTop).
        /// </summary>
        public static string Options_AlwaysOnTop {
            get {
                return ResourceManager.GetString("Options_AlwaysOnTop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_AlwaysOnTopTip).
        /// </summary>
        public static string Options_AlwaysOnTopTip {
            get {
                return ResourceManager.GetString("Options_AlwaysOnTopTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_MinimizeToTray).
        /// </summary>
        public static string Options_MinimizeToTray {
            get {
                return ResourceManager.GetString("Options_MinimizeToTray", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_MinimizeToTrayTip).
        /// </summary>
        public static string Options_MinimizeToTrayTip {
            get {
                return ResourceManager.GetString("Options_MinimizeToTrayTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_ExitToTray).
        /// </summary>
        public static string Options_ExitToTray {
            get {
                return ResourceManager.GetString("Options_ExitToTray", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_ExitToTrayTip).
        /// </summary>
        public static string Options_ExitToTrayTip {
            get {
                return ResourceManager.GetString("Options_ExitToTrayTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_TabColors).
        /// </summary>
        public static string Options_TabColors {
            get {
                return ResourceManager.GetString("Options_TabColors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_ProbeBackground).
        /// </summary>
        public static string Options_ProbeBackground {
            get {
                return ResourceManager.GetString("Options_ProbeBackground", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_ColorInactive).
        /// </summary>
        public static string Options_ColorInactive {
            get {
                return ResourceManager.GetString("Options_ColorInactive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_ColorUp).
        /// </summary>
        public static string Options_ColorUp {
            get {
                return ResourceManager.GetString("Options_ColorUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_ColorDown).
        /// </summary>
        public static string Options_ColorDown {
            get {
                return ResourceManager.GetString("Options_ColorDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_ColorIndeterminate).
        /// </summary>
        public static string Options_ColorIndeterminate {
            get {
                return ResourceManager.GetString("Options_ColorIndeterminate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_ColorError).
        /// </summary>
        public static string Options_ColorError {
            get {
                return ResourceManager.GetString("Options_ColorError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_ProbeForeground).
        /// </summary>
        public static string Options_ProbeForeground {
            get {
                return ResourceManager.GetString("Options_ProbeForeground", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_StatsForeground).
        /// </summary>
        public static string Options_StatsForeground {
            get {
                return ResourceManager.GetString("Options_StatsForeground", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_AliasForeground).
        /// </summary>
        public static string Options_AliasForeground {
            get {
                return ResourceManager.GetString("Options_AliasForeground", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_RestoreDefaults).
        /// </summary>
        public static string Options_RestoreDefaults {
            get {
                return ResourceManager.GetString("Options_RestoreDefaults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Options_SaveAsDefaults).
        /// </summary>
        public static string Options_SaveAsDefaults {
            get {
                return ResourceManager.GetString("Options_SaveAsDefaults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Popup_OpenHistory).
        /// </summary>
        public static string Popup_OpenHistory {
            get {
                return ResourceManager.GetString("Popup_OpenHistory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (StatusHistory_Filter).
        /// </summary>
        public static string StatusHistory_Filter {
            get {
                return ResourceManager.GetString("StatusHistory_Filter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (StatusHistory_Include).
        /// </summary>
        public static string StatusHistory_Include {
            get {
                return ResourceManager.GetString("StatusHistory_Include", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (StatusHistory_Start).
        /// </summary>
        public static string StatusHistory_Start {
            get {
                return ResourceManager.GetString("StatusHistory_Start", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (StatusHistory_Stop).
        /// </summary>
        public static string StatusHistory_Stop {
            get {
                return ResourceManager.GetString("StatusHistory_Stop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (StatusHistory_Export).
        /// </summary>
        public static string StatusHistory_Export {
            get {
                return ResourceManager.GetString("StatusHistory_Export", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (TraceRoute_Header).
        /// </summary>
        public static string TraceRoute_Header {
            get {
                return ResourceManager.GetString("TraceRoute_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (TraceRoute_Watermark).
        /// </summary>
        public static string TraceRoute_Watermark {
            get {
                return ResourceManager.GetString("TraceRoute_Watermark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Usage_Header).
        /// </summary>
        public static string Usage_Header {
            get {
                return ResourceManager.GetString("Usage_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Usage_Options).
        /// </summary>
        public static string Usage_Options {
            get {
                return ResourceManager.GetString("Usage_Options", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Usage_Interval).
        /// </summary>
        public static string Usage_Interval {
            get {
                return ResourceManager.GetString("Usage_Interval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Usage_IntervalRange).
        /// </summary>
        public static string Usage_IntervalRange {
            get {
                return ResourceManager.GetString("Usage_IntervalRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Usage_Timeout).
        /// </summary>
        public static string Usage_Timeout {
            get {
                return ResourceManager.GetString("Usage_Timeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Usage_TimeoutRange).
        /// </summary>
        public static string Usage_TimeoutRange {
            get {
                return ResourceManager.GetString("Usage_TimeoutRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Usage_Minimized).
        /// </summary>
        public static string Usage_Minimized {
            get {
                return ResourceManager.GetString("Usage_Minimized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Usage_Hostname).
        /// </summary>
        public static string Usage_Hostname {
            get {
                return ResourceManager.GetString("Usage_Hostname", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Usage_HostnameMulti).
        /// </summary>
        public static string Usage_HostnameMulti {
            get {
                return ResourceManager.GetString("Usage_HostnameMulti", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Usage_File).
        /// </summary>
        public static string Usage_File {
            get {
                return ResourceManager.GetString("Usage_File", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Usage_Examples).
        /// </summary>
        public static string Usage_Examples {
            get {
                return ResourceManager.GetString("Usage_Examples", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (FloodHost_Start).
        /// </summary>
        public static string FloodHost_Start {
            get {
                return ResourceManager.GetString("FloodHost_Start", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (FloodHost_Stop).
        /// </summary>
        public static string FloodHost_Stop {
            get {
                return ResourceManager.GetString("FloodHost_Stop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (TraceRoute_Start).
        /// </summary>
        public static string TraceRoute_Start {
            get {
                return ResourceManager.GetString("TraceRoute_Start", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_InvalidColumns).
        /// </summary>
        public static string Msg_InvalidColumns {
            get {
                return ResourceManager.GetString("Msg_InvalidColumns", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_NoHosts).
        /// </summary>
        public static string Msg_NoHosts {
            get {
                return ResourceManager.GetString("Msg_NoHosts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_InvalidInterval).
        /// </summary>
        public static string Msg_InvalidInterval {
            get {
                return ResourceManager.GetString("Msg_InvalidInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_InvalidTimeout).
        /// </summary>
        public static string Msg_InvalidTimeout {
            get {
                return ResourceManager.GetString("Msg_InvalidTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_InvalidThreshold).
        /// </summary>
        public static string Msg_InvalidThreshold {
            get {
                return ResourceManager.GetString("Msg_InvalidThreshold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_InvalidAutoDismiss).
        /// </summary>
        public static string Msg_InvalidAutoDismiss {
            get {
                return ResourceManager.GetString("Msg_InvalidAutoDismiss", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_InvalidTtl).
        /// </summary>
        public static string Msg_InvalidTtl {
            get {
                return ResourceManager.GetString("Msg_InvalidTtl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_InvalidPacketSize).
        /// </summary>
        public static string Msg_InvalidPacketSize {
            get {
                return ResourceManager.GetString("Msg_InvalidPacketSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_InvalidSmtpServer).
        /// </summary>
        public static string Msg_InvalidSmtpServer {
            get {
                return ResourceManager.GetString("Msg_InvalidSmtpServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_InvalidSmtpPort).
        /// </summary>
        public static string Msg_InvalidSmtpPort {
            get {
                return ResourceManager.GetString("Msg_InvalidSmtpPort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_InvalidRecipient).
        /// </summary>
        public static string Msg_InvalidRecipient {
            get {
                return ResourceManager.GetString("Msg_InvalidRecipient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_InvalidFrom).
        /// </summary>
        public static string Msg_InvalidFrom {
            get {
                return ResourceManager.GetString("Msg_InvalidFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_InvalidUsername).
        /// </summary>
        public static string Msg_InvalidUsername {
            get {
                return ResourceManager.GetString("Msg_InvalidUsername", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_PathNotFound).
        /// </summary>
        public static string Msg_PathNotFound {
            get {
                return ResourceManager.GetString("Msg_PathNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_PathNotFound2).
        /// </summary>
        public static string Msg_PathNotFound2 {
            get {
                return ResourceManager.GetString("Msg_PathNotFound2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_InvalidColor).
        /// </summary>
        public static string Msg_InvalidColor {
            get {
                return ResourceManager.GetString("Msg_InvalidColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_AudioPlayFailed).
        /// </summary>
        public static string Msg_AudioPlayFailed {
            get {
                return ResourceManager.GetString("Msg_AudioPlayFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_TestFailed).
        /// </summary>
        public static string Msg_TestFailed {
            get {
                return ResourceManager.GetString("Msg_TestFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_ExportTitle).
        /// </summary>
        public static string Msg_ExportTitle {
            get {
                return ResourceManager.GetString("Msg_ExportTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_ExportedTo).
        /// </summary>
        public static string Msg_ExportedTo {
            get {
                return ResourceManager.GetString("Msg_ExportedTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_ReadConfigFailed).
        /// </summary>
        public static string Msg_ReadConfigFailed {
            get {
                return ResourceManager.GetString("Msg_ReadConfigFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_FavoriteNotFound).
        /// </summary>
        public static string Msg_FavoriteNotFound {
            get {
                return ResourceManager.GetString("Msg_FavoriteNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_LogWriteFailed).
        /// </summary>
        public static string Msg_LogWriteFailed {
            get {
                return ResourceManager.GetString("Msg_LogWriteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Msg_AudioFailed).
        /// </summary>
        public static string Msg_AudioFailed {
            get {
                return ResourceManager.GetString("Msg_AudioFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help_ForkSubtitle).
        /// </summary>
        public static string Help_ForkSubtitle {
            get {
                return ResourceManager.GetString("Help_ForkSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help_BasedOn).
        /// </summary>
        public static string Help_BasedOn {
            get {
                return ResourceManager.GetString("Help_BasedOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (Help_License).
        /// </summary>
        public static string Help_License {
            get {
                return ResourceManager.GetString("Help_License", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (FileBrowser_Title).
        /// </summary>
        public static string FileBrowser_Title {
            get {
                return ResourceManager.GetString("FileBrowser_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (FileBrowser_TitleFolder).
        /// </summary>
        public static string FileBrowser_TitleFolder {
            get {
                return ResourceManager.GetString("FileBrowser_TitleFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (FileBrowser_Up).
        /// </summary>
        public static string FileBrowser_Up {
            get {
                return ResourceManager.GetString("FileBrowser_Up", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string (FileBrowser_Go).
        /// </summary>
        public static string FileBrowser_Go {
            get {
                return ResourceManager.GetString("FileBrowser_Go", resourceCulture);
            }
        }
    }
}
